// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxAx0OS-dP_HXnpOlkuZq7lR-5EQ4UAxI',
    appId: '1:300626943188:web:d9a2f75960ecceb5b5af41',
    messagingSenderId: '300626943188',
    projectId: 'sjedrs-af55e',
    authDomain: 'sjedrs-af55e.firebaseapp.com',
    databaseURL: 'https://sjedrs-af55e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sjedrs-af55e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHa0-5-gKvOnjYp7hC4R672qi11MEpCo',
    appId: '1:300626943188:android:e166353582babe7ab5af41',
    messagingSenderId: '300626943188',
    projectId: 'sjedrs-af55e',
    databaseURL: 'https://sjedrs-af55e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sjedrs-af55e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqRL9ropnTuLKd_JfRl1PXWliXQ_qfuBw',
    appId: '1:300626943188:ios:e212bcf17757870eb5af41',
    messagingSenderId: '300626943188',
    projectId: 'sjedrs-af55e',
    databaseURL: 'https://sjedrs-af55e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sjedrs-af55e.appspot.com',
    iosBundleId: 'com.example.sjedrsmobile',
  );
}
